import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCAD, formatPct, formatShort } from './formatters';
import type { Scenario } from '../types/scenario';
import type { ComputedScenario } from '../types/computed';

interface ReportInput {
  scenario: Scenario;
  computed: ComputedScenario;
}

const ACCENT: [number, number, number] = [16, 185, 129]; // emerald green
const HEADER_BG: [number, number, number] = ACCENT;
const TEXT_DARK: [number, number, number] = [15, 23, 42];
const TEXT_MED: [number, number, number] = [51, 65, 85];
const TEXT_LIGHT: [number, number, number] = [100, 116, 139];

export function generatePDFReport({ scenario, computed }: ReportInput) {
  const doc = new jsPDF('portrait', 'mm', 'letter');
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  // ── Helper: Add footer on every page ───────────────────────────
  function addFooter() {
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setTextColor(...TEXT_LIGHT);
      doc.text('Generated by CDN Tax & Investment Model', margin, doc.internal.pageSize.getHeight() - 8);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, doc.internal.pageSize.getHeight() - 8, { align: 'right' });
    }
  }

  // ── 1. Header bar ─────────────────────────────────────────────
  doc.setFillColor(...ACCENT);
  doc.rect(0, 0, pageWidth, 18, 'F');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text('Financial Plan Summary', margin, 12);

  // Scenario name + date
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...TEXT_DARK);
  y = 26;
  doc.text(scenario.name, margin, y);
  doc.setTextColor(...TEXT_LIGHT);
  doc.text(new Date().toLocaleDateString('en-CA'), pageWidth - margin, y, { align: 'right' });
  y += 6;

  // ── 2. Assumptions box ────────────────────────────────────────
  const a = scenario.assumptions;
  const numYears = scenario.years.length;
  const startYear = scenario.years[0]?.year ?? new Date().getFullYear();

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: 'plain',
    styles: { fontSize: 7.5, cellPadding: 1.5, textColor: TEXT_MED },
    headStyles: { fillColor: [241, 245, 249], textColor: TEXT_DARK, fontStyle: 'bold', fontSize: 7.5 },
    head: [['Assumption', 'Value', 'Assumption', 'Value']],
    body: [
      ['Province', a.province, 'Start Year', String(startYear)],
      ['Years', String(numYears), 'Inflation', formatPct(a.inflationRate)],
      ['Equity Return', formatPct(a.assetReturns.equity), 'Fixed Return', formatPct(a.assetReturns.fixedIncome)],
      ['Cash Return', formatPct(a.assetReturns.cash), 'Savings Return', formatPct(a.assetReturns.savings)],
    ],
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: contentWidth * 0.2 },
      1: { cellWidth: contentWidth * 0.3 },
      2: { fontStyle: 'bold', cellWidth: contentWidth * 0.2 },
      3: { cellWidth: contentWidth * 0.3 },
    },
  });
  y = (doc as any).lastAutoTable.finalY + 6;

  // ── 3. Lifetime KPIs table ────────────────────────────────────
  const analytics = computed.analytics;
  const lastYear = computed.years[computed.years.length - 1];
  const finalNW = lastYear?.accounts.netWorth ?? 0;

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2.5, textColor: TEXT_DARK },
    headStyles: { fillColor: HEADER_BG, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    head: [['Lifetime Metric', 'Value']],
    body: [
      ['Lifetime Gross Income', formatCAD(analytics.lifetimeGrossIncome)],
      ['Lifetime Total Tax', formatCAD(analytics.lifetimeTotalTax)],
      ['Lifetime CPP + EI', formatCAD(analytics.lifetimeCPPEI)],
      ['Lifetime After-Tax Income', formatCAD(analytics.lifetimeAfterTaxIncome)],
      ['Lifetime Avg Tax Rate', formatPct(analytics.lifetimeAvgTaxRate)],
      ['Lifetime Avg All-In Rate', formatPct(analytics.lifetimeAvgAllInRate)],
      ['Lifetime Cash Flow', formatCAD(analytics.lifetimeCashFlow)],
      ['Final Net Worth', formatCAD(finalNW)],
    ],
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: contentWidth * 0.5 },
      1: { halign: 'right' },
    },
  });
  y = (doc as any).lastAutoTable.finalY + 6;

  // ── 4. Annual Summary table ───────────────────────────────────
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: 'striped',
    styles: { fontSize: 7.5, cellPadding: 1.8, textColor: TEXT_DARK },
    headStyles: { fillColor: HEADER_BG, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7.5 },
    head: [['Year', 'Gross Income', 'Total Tax', 'After-Tax', 'Net Worth', 'Marg. Rate']],
    body: computed.years.map(yr => [
      String(yr.year),
      formatCAD(yr.waterfall.grossIncome),
      formatCAD(yr.tax.totalIncomeTax + yr.cpp.totalCPPPaid + yr.ei.totalEI),
      formatCAD(yr.waterfall.afterTaxIncome),
      formatCAD(yr.accounts.netWorth),
      formatPct(yr.tax.marginalCombinedRate),
    ]),
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 16 },
      1: { halign: 'right' },
      2: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'right' },
      5: { halign: 'right' },
    },
  });

  // ── 5. Account Balances table (new page) ──────────────────────
  doc.addPage();
  y = 14;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEXT_DARK);
  doc.text('Account Balances', margin, y);
  y += 6;

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: 'striped',
    styles: { fontSize: 7.5, cellPadding: 1.8, textColor: TEXT_DARK },
    headStyles: { fillColor: HEADER_BG, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7.5 },
    head: [['Year', 'RRSP', 'TFSA', 'FHSA', 'Non-Reg', 'Savings', 'Net Worth']],
    body: computed.years.map(yr => [
      String(yr.year),
      formatCAD(yr.accounts.rrspEOY),
      formatCAD(yr.accounts.tfsaEOY),
      formatCAD(yr.accounts.fhsaEOY),
      formatCAD(yr.accounts.nonRegEOY),
      formatCAD(yr.accounts.savingsEOY),
      formatCAD(yr.accounts.netWorth),
    ]),
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 16 },
      1: { halign: 'right' },
      2: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'right' },
      5: { halign: 'right' },
      6: { halign: 'right', fontStyle: 'bold' },
    },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // ── 6. Tax Breakdown table ────────────────────────────────────
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEXT_DARK);
  doc.text('Tax Breakdown', margin, y);
  y += 6;

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: 'striped',
    styles: { fontSize: 7.5, cellPadding: 1.8, textColor: TEXT_DARK },
    headStyles: { fillColor: HEADER_BG, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7.5 },
    head: [['Year', 'Federal', 'Provincial', 'CPP', 'EI', 'Total', 'Avg Rate']],
    body: computed.years.map(yr => {
      const totalTax = yr.tax.totalIncomeTax + yr.cpp.totalCPPPaid + yr.ei.totalEI;
      return [
        String(yr.year),
        formatCAD(yr.tax.federalTaxPayable),
        formatCAD(yr.tax.provincialTaxPayable),
        formatCAD(yr.cpp.totalCPPPaid),
        formatCAD(yr.ei.totalEI),
        formatCAD(totalTax),
        formatPct(yr.tax.avgAllInRate),
      ];
    }),
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 16 },
      1: { halign: 'right' },
      2: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'right' },
      5: { halign: 'right', fontStyle: 'bold' },
      6: { halign: 'right' },
    },
  });

  // ── Footer ────────────────────────────────────────────────────
  addFooter();

  // ── Download ──────────────────────────────────────────────────
  const filename = `${scenario.name.replace(/[^a-zA-Z0-9]/g, '_')}_Report.pdf`;
  doc.save(filename);
}
